// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db_access} from '../models';

export function DebugOutput(arg1:string):void;

export function Query(arg1:db_access.Query):Promise<Array<db_access.ResultsByDomain>>;

export function WriteToClipboard(arg1:string):void;
