// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugOutput(arg1) {
  return window['go']['main']['App']['DebugOutput'](arg1);
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}

export function WriteToClipboard(arg1) {
  return window['go']['main']['App']['WriteToClipboard'](arg1);
}
