// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db_access} from '../models';

export function Query(arg1:string):Promise<Array<db_access.ResultsByDomain>>;
